### ISSUE TITLE
"Dprint cannot format no path" log spam

### ISSUE THREAD

**Issue by jonathanj** [dprint/dprint-intellij#56]
I happened to look at the Dprint logs in IntelliJ today (I was debugging a config issue), and noticed that this message is spammed a lot. Pretty much any interaction with IntelliJ (focusing the window, moving the cursor, etc.) triggers a cluster of these.

[This code](https://github.com/dprint/dprint-intellij/blob/main/src/main/kotlin/com/dprint/formatter/DprintExternalFormatter.kt#L59) seems to be responsible for logging it, unfortunately it's not actually clear what "no path" _is_ if it's not a valid virtual file. There is a comment above this code that indicates that scratch files (and possibly other types of files?) are ignored, so maybe it's one of these?

Is this anything to be concerned about from a performance point of view? I'm not even sure whether this is logged if the dprint logging window is not active, so maybe just a question for my own curiosity.

```
2023 08 12 14:21:31:  Dprint cannot format no path, IntelliJ formatter will be used.
2023 08 12 14:21:31:  Dprint cannot format no path, IntelliJ formatter will be used.
2023 08 12 14:21:31:  Dprint cannot format no path, IntelliJ formatter will be used.
2023 08 12 14:21:31:  Dprint cannot format no path, IntelliJ formatter will be used.
2023 08 12 14:21:31:  Dprint cannot format no path, IntelliJ formatter will be used.
2023 08 12 14:21:31:  Dprint cannot format no path, IntelliJ formatter will be used.
2023 08 12 14:21:32:  Dprint cannot format no path, IntelliJ formatter will be used.
2023 08 12 14:21:32:  Dprint cannot format no path, IntelliJ formatter will be used.
2023 08 12 14:21:32:  Dprint cannot format no path, IntelliJ formatter will be used.
2023 08 12 14:21:32:  Dprint cannot format no path, IntelliJ formatter will be used.
2023 08 12 14:21:32:  Dprint cannot format no path, IntelliJ formatter will be used.
2023 08 12 14:21:32:  Dprint cannot format no path, IntelliJ formatter will be used.
2023 08 12 14:21:32:  Dprint cannot format no path, IntelliJ formatter will be used.
2023 08 12 14:21:32:  Dprint cannot format no path, IntelliJ formatter will be used.
2023 08 12 14:21:32:  Dprint cannot format no path, IntelliJ formatter will be used.
```

**Comment by ryan-rushton** [comment]
I thought this should only happen for cases like scratch files where it their usage is pretty infrequent. I haven't noticed the log span myself and while I don't think it has any real performance impact I might remove the log into IJ logs to be safe. Thanks for the report.

**Comment by jonathanj** [comment]
Thank you so much for taking the time to look at and improve this @ryan-rushton!
