### ISSUE TITLE
Cannot detect ".dprint.jsonc" config file

### ISSUE THREAD

**Issue by akkadaya** [dprint/dprint-intellij#92]
I'm using version 0.7.0, I had `.dprint.jsonc` in my project root but it says
> INFO - #com.dprint.utils.FileUtils - Could not detect a config file

renaming it to `.dprint.json` fixed the issue but I haven't tried the other config file names
> Setup dprint
After [installing](https://dprint.dev/install), the main part of getting setup is to create a dprint.json/dprint.jsonc, or hidden .dprint.json/.dprint.jsonc file in your project.

**Comment by ryan-rushton** [comment]
Thanks, I will do an update for this.

**Comment by ryan-rushton** [comment]
This should be fixed in the version I just published
